### ISSUE TITLE
glob pattern does not allow for ignored patterns

### ISSUE THREAD

**Issue by kenhowardpdx** [jonschlinkert/copy#10]
I have a case where I want to copy all files out of my `src` directory except `*.ts` files. I'd expect the following code to prevent `*.ts` files from being copied to the destination folder.

```
copy(['src/**/*', '!src/**/*.ts'], 'dest', function (err, file) {
  // done
});
```

**Comment by jonschlinkert** [comment]
try `'!**/src/**/*.ts'`, to ensure the path matches if node-gob makes the pattern absolute.

**Comment by jonschlinkert** [comment]
closing since the solution I mentioned should work, @kenhowardpdx please reopen if you're stilling having the problem

**Comment by havenchyk** [comment]
@jonschlinkert it doesn't work for me, could you please reopen?
