### ISSUE TITLE
request: add option `--quiet`

### ISSUE THREAD

**Issue by alexander-akait** [jonschlinkert/copy#12]
disable all output except errors

**Comment by alexander-akait** [comment]
@jonschlinkert i use npm `scripts` for building my projects and output is clogs my console :sob:

**Comment by jonschlinkert** [comment]
I just pushed up support for `--verbose, -v`, so it will be silent by default once it's published

**Comment by alexander-akait** [comment]
@jonschlinkert can i do PR?

**Comment by jonschlinkert** [comment]
sure, against this branch: https://github.com/jonschlinkert/copy/tree/cli-cwd
