### ISSUE TITLE
Cli doesn't allow `**` globbing patterns

### ISSUE THREAD

**Issue by ashleahhill** [jonschlinkert/copy#13]
When using copy via the cli, you can only use simple patterns like the one in the example. Using the API directly works fine with the same globs. I am running Windows 10 (pre-anniversary update)
## Fails

Running from the command line.

``` bash
$ copy src/**/*.html foo
# The syntax of the command is incorrect.
```

``` bash
$ copy "src/**/*.html" foo

# src/**/*.html
# The filename, directory name, or volume label syntax is incorrect.
#        0 file(s) copied.
```
## Works

Running from script

``` javascript
copy('src/**/*.html', 'bar', function (err, file) {
  if (err ) console.log(err);
  console.log('files copied');
})
```

**Comment by jonschlinkert** [comment]
Hmm, even with quotes? I'll look into it. We might need to do some kind of escaping on the pattern, or perhaps the cwd isn't being set properly. thanks for reporting.
