### ISSUE TITLE
Breaks in Node 10.x

### ISSUE THREAD

**Issue by rijkvanzanten** [jonschlinkert/copy#28]
When using Node 10, the plugin creates new files in the right place, but doesn't copy over the file contents

**Comment by doowb** [comment]
@rijkvanzanten can you post the code used to reproduce this and which operating system you're using?

**Comment by rijkvanzanten** [comment]
I'm using an NPM script called `copy`:

`copy \"./{interfaces,pages,listings}/**/meta.json\" dist` which copies over all `meta.json` files from those three folders into `dist` (while keeping the directory structure intact.

I'm using macOS High Sierra 10.13.3

**Comment by doowb** [comment]
I'm able to verify that something changed between node `v9.11.1` and `v10.0.0` but I haven't dug in to figure out the difference yet.

**Comment by Elephant-Vessel** [comment]
Same here, using win 7.

**Comment by tmcw** [comment]
Looks like the same issue as in cp-file: here's the PR that fixed that project https://github.com/sindresorhus/cp-file/pull/26 - the gist is that you'll need to switch from `.on('readable'` to `.once('readable'`.

**Comment by doowb** [comment]
Thanks @tmcw!

**Comment by doowb** [comment]
Published a bug fix as patch `0.3.2`. I checked different versions of `node` before publishing (and travis will also do the check) and everything works back to `node@0.10.0`.
